/*
 * LarvaStageAttributesCustomizer.java
 */

package wts.models.DisMELS.IBMs.POP.Larva;

import wts.models.DisMELS.IBMs.POP.NewAttributes;
import wts.models.DisMELS.framework.*;
import wts.models.DisMELS.gui.AttributesCustomizer;

/**
 * Customizer for the POP LarvaStageAttributes class with maternal effects.
 */
public class LarvaStageAttributesCustomizer extends AttributesCustomizer {

    private LarvaStageAttributes attributes = null;
    
    /**
     * Creates new customizer LarvaStageAttributesCustomizer
     */
    public LarvaStageAttributesCustomizer() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        czrStandardAttributes = new wts.models.DisMELS.gui.AbstractLHSAttributesCustomizer();
        jPanel2 = new javax.swing.JPanel();
        jtfSize = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfWeight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfMatAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(czrStandardAttributes, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Additional attributes"));

        jtfSize.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfSize.setText("0");
        jtfSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSizeActionPerformed(evt);
            }
        });

        jLabel1.setText("Size (mm)");

        jtfWeight.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfWeight.setText("0");
        jtfWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfWeightActionPerformed(evt);
            }
        });

        jLabel2.setText("Weight (g)");
        jLabel2.setToolTipText("");

        jtfMatAge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfMatAge.setText("0");
        jtfMatAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMatAgeActionPerformed(evt);
            }
        });

        jLabel3.setText("Maternal age (years)");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jtfSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jtfMatAge)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jtfWeight, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .add(0, 0, 0))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfWeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfMatAge, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSizeActionPerformed
        Double n = new Double(jtfSize.getText());
        attributes.setValue(NewAttributes.PROP_size,n);
    }//GEN-LAST:event_jtfSizeActionPerformed

    private void jtfWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfWeightActionPerformed
        Double n = new Double(jtfWeight.getText());
        attributes.setValue(NewAttributes.PROP_weight,n);
    }//GEN-LAST:event_jtfWeightActionPerformed

    private void jtfMatAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMatAgeActionPerformed
        Double n = new Double(jtfMatAge.getText());
        attributes.setValue(LarvaStageAttributes.PROP_MaternalAge,n);
    }//GEN-LAST:event_jtfMatAgeActionPerformed

    @Override
    public void setObject(Object bean) {
        if (bean instanceof LarvaStageAttributes) {
            setAttributes((LarvaStageAttributes) bean);
        }
    }
    
    @Override
    public LarvaStageAttributes getAttributes() {
        return attributes;
    }
    
    @Override
    public void setAttributes(LifeStageAttributesInterface newAtts) {
        if (newAtts instanceof LarvaStageAttributes) {
            attributes = (LarvaStageAttributes) newAtts;
            czrStandardAttributes.setObject(attributes);
            Double d = null;
            jtfSize.setText(attributes.getValue(NewAttributes.PROP_size,d).toString());
            jtfWeight.setText(attributes.getValue(NewAttributes.PROP_weight,d).toString());
            jtfMatAge.setText(attributes.getValue(LarvaStageAttributes.PROP_MaternalAge,d).toString());
        }
    }
    
    @Override
    public void showHorizPos(boolean b) {
        czrStandardAttributes.showHorizPos(b);
        revalidate();
    }
    
    @Override
    public void showVertPos(boolean b) {
        czrStandardAttributes.showVertPos(b);
        revalidate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private wts.models.DisMELS.gui.AbstractLHSAttributesCustomizer czrStandardAttributes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtfMatAge;
    private javax.swing.JTextField jtfSize;
    private javax.swing.JTextField jtfWeight;
    // End of variables declaration//GEN-END:variables
    
}
